# fly.toml app configuration file generated for cliet-tableaux-v2-api on 2024-07-02T14:57:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cliet-tableaux-v2-api'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  # auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
